// Generated by CoffeeScript 1.9.3
(function() {
  window.config = {
    github: {
      apiurl: "https://serverName/api/v3",
      username: "ssergienko",
      password: "",
      auth: "basic"
    },
    marionetteRepo: {
      user: "marionettejs",
      repo: "backbone.marionette",
      contributersUrl: "https://api.github.com/repos/marionettejs/backbone.marionette/contributors",
      forksUrl: "https://api.github.com/repos/marionettejs/backbone.marionette/forks"
    }
  };

}).call(this);
