// Generated by CoffeeScript 1.9.3
(function() {
  describe("Contributers.Controller", function() {
    return it("test method exists and executes", function() {
      return expect(GithubApp.GithubApp.Contributers.Controller.test()).toEqual('test');
    });
  });

}).call(this);
