// Generated by CoffeeScript 1.9.3
(function() {
  GithubApp.module("GithubApp.Forks", function(Forks) {
    return Forks.ForksModel = Backbone.Model.extend({
      url: config.marionetteRepo.forksUrl
    });
  });

}).call(this);
